services:
  - type: web
    name: gestao-clientes-api
    env: node
    rootDir: backend
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
